namespace FSH.Starter.WebApi.MicroFinance.Application.CollateralInsurances.Get.v1;

public sealed record CollateralInsuranceResponse(
    DefaultIdType Id,
    DefaultIdType CollateralId,
    string PolicyNumber,
    string InsurerName,
    string InsuranceType,
    string Status,
    decimal CoverageAmount,
    decimal PremiumAmount,
    decimal Deductible,
    DateOnly EffectiveDate,
    DateOnly ExpiryDate,
    DateOnly? RenewalDate,
    string? InsurerContact,
    string? InsurerPhone,
    string? InsurerEmail,
    bool IsMfiAsBeneficiary,
    string? BeneficiaryName,
    string? PolicyDocumentPath,
    DateOnly? LastPremiumPaidDate,
    DateOnly? NextPremiumDueDate,
    string? Notes,
    int RenewalReminderDays,
    bool AutoRenewal);
