using FSH.Starter.WebApi.Store.Application.ItemSuppliers.Specs;
using Store.Domain.Exceptions.ItemSupplier;

namespace FSH.Starter.WebApi.Store.Application.ItemSuppliers.Create.v1;

/// <summary>
/// Handler for creating an item-supplier relationship.
/// </summary>
public sealed class CreateItemSupplierHandler(
    [FromKeyedServices("store:itemsuppliers")] IRepository<ItemSupplier> repository,
    [FromKeyedServices("store:itemsuppliers")] IReadRepository<ItemSupplier> readRepository,
    [FromKeyedServices("store:items")] IReadRepository<Item> itemRepository,
    [FromKeyedServices("store:suppliers")] IReadRepository<Supplier> supplierRepository)
    : IRequestHandler<CreateItemSupplierCommand, CreateItemSupplierResponse>
{
    public async Task<CreateItemSupplierResponse> Handle(CreateItemSupplierCommand request, CancellationToken cancellationToken)
    {
        // Check for duplicate item-supplier relationship
        var existing = await readRepository.FirstOrDefaultAsync(
            new ItemSupplierByItemAndSupplierSpec(request.ItemId, request.SupplierId),
            cancellationToken);

        if (existing is not null)
        {
            throw new DuplicateItemSupplierException(request.ItemId, request.SupplierId);
        }

        var itemSupplier = ItemSupplier.Create(
            request.ItemId,
            request.SupplierId,
            request.UnitCost,
            request.LeadTimeDays,
            request.MinimumOrderQuantity,
            request.SupplierPartNumber,
            request.PackagingQuantity,
            request.IsPreferred);

        // Fetch Item and Supplier to auto-generate Name
        var item = await itemRepository.GetByIdAsync(request.ItemId, cancellationToken);
        var supplier = await supplierRepository.GetByIdAsync(request.SupplierId, cancellationToken);

        // Auto-generate Name from SupplierCode + ItemName
        string autoGeneratedName = $"{supplier?.Code} - {item?.Name}";
        itemSupplier.Name = autoGeneratedName;

        // Set inherited AuditableEntity properties
        if (!string.IsNullOrWhiteSpace(request.Description))
        {
            itemSupplier.Description = request.Description;
        }
        if (!string.IsNullOrWhiteSpace(request.Notes))
        {
            itemSupplier.Notes = request.Notes;
        }

        await repository.AddAsync(itemSupplier, cancellationToken);
        await repository.SaveChangesAsync(cancellationToken);

        return new CreateItemSupplierResponse(itemSupplier.Id);
    }
}
