namespace Accounting.Application.Projects.Responses;

/// <summary>
/// Response model representing a project entity.
/// Contains project information including timeline, budget, and performance metrics.
/// </summary>
public class ProjectResponse(
    DateTime startDate,
    DateTime? endDate,
    decimal budgetedAmount,
    string? clientName,
    string? projectManager,
    string? department,
    decimal actualCost,
    decimal actualRevenue) : BaseDto
{
    /// <summary>
    /// Date when the project started.
    /// </summary>
    public DateTime StartDate { get; set; } = startDate;
    
    /// <summary>
    /// Date when the project ended (if completed).
    /// </summary>
    public DateTime? EndDate { get; set; } = endDate;
    
    /// <summary>
    /// Originally budgeted amount for the project.
    /// </summary>
    public decimal BudgetedAmount { get; set; } = budgetedAmount;
    
    /// <summary>
    /// Name of the client for this project.
    /// </summary>
    public string? ClientName { get; set; } = clientName;
    
    /// <summary>
    /// Name of the project manager responsible for this project.
    /// </summary>
    public string? ProjectManager { get; set; } = projectManager;
    
    /// <summary>
    /// Department or division responsible for the project.
    /// </summary>
    public string? Department { get; set; } = department;
    
    /// <summary>
    /// Actual cost incurred for the project to date.
    /// </summary>
    public decimal ActualCost { get; set; } = actualCost;
    
    /// <summary>
    /// Actual revenue generated by the project to date.
    /// </summary>
    public decimal ActualRevenue { get; set; } = actualRevenue;
}
