namespace FSH.Starter.WebApi.MicroFinance.Application.DebtSettlements.Get.v1;

public sealed record DebtSettlementResponse(
    DefaultIdType Id,
    string ReferenceNumber,
    DefaultIdType CollectionCaseId,
    DefaultIdType LoanId,
    DefaultIdType MemberId,
    string SettlementType,
    string Status,
    decimal OriginalOutstanding,
    decimal SettlementAmount,
    decimal DiscountAmount,
    decimal DiscountPercentage,
    decimal AmountPaid,
    decimal RemainingBalance,
    int? NumberOfInstallments,
    decimal? InstallmentAmount,
    DateOnly ProposedDate,
    DateOnly? ApprovedDate,
    DateOnly DueDate,
    DateOnly? CompletedDate,
    string Terms,
    string? Justification,
    DefaultIdType ProposedById,
    DefaultIdType? ApprovedById);
