namespace FSH.Starter.WebApi.MicroFinance.Application.InvestmentAccounts.Get.v1;

public sealed record InvestmentAccountResponse(
    DefaultIdType Id,
    DefaultIdType MemberId,
    string AccountNumber,
    string Status,
    string RiskProfile,
    decimal TotalInvested,
    decimal CurrentValue,
    decimal TotalGainLoss,
    decimal TotalGainLossPercent,
    decimal RealizedGains,
    decimal UnrealizedGains,
    decimal TotalDividends,
    int HoldingsCount,
    DateOnly? FirstInvestmentDate,
    DateOnly? LastTransactionDate,
    DefaultIdType? AssignedAdvisorId,
    bool HasSip,
    decimal? SipAmount,
    string? SipFrequency,
    DateOnly? NextSipDate,
    string? InvestmentGoal,
    DateOnly? TargetDate,
    decimal? TargetAmount);
